language: objective-c
osx_image: xcode8.3

env:
  global:
    - PROJECT=Cascade.xcodeproj
    - SCHEME=Cascade
script:
  xcodebuild -project "$PROJECT" -scheme "$SCHEME" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
