language: objective-c
osx_image: xcode8.3

env:
  global:
    - PROJECT=Cascade.xcodeproj
    - SCHEME=Cascade

script:
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)